title: Moja Strona o Cyberbezpieczeństwie
description: Strona poświęcona tematyce cyberbezpieczeństwa.
baseurl: "" # pozostań pusty
url: "https://cybrivium.github.io"
theme: minimal-mistakes-jekyll

# dodatkowe opcje motywu
logo: /assets/images/logo.png # dodaj swoje logo
social_links:
  - name: GitHub
    url: https://github.com/cybrivium
    icon: fab fa-github
